### ISSUE TITLE
Getting "BadRequest:Failed to find metric configuration for provider: " error while querying the Azure SQL datawarehouse metrics

### ISSUE THREAD

**Issue by baburajvelayudhan** [Azure/azure-libraries-for-java#688]
I am getting the below error while querying the Azure SQL Datawarehouse metrics

WARN [2019-01-22 06:09:17,006] azure: Failed to get azure points for customer: master
! **com.microsoft.azure.management.monitor.ErrorResponseException: Status code 400, {"code":"BadRequest","message":"Failed to find metric configuration for provider: Microsoft.Sql, resource Type: servers/databases, metric: log_write_percent**, Valid metrics: cpu_percent,physical_data_read_percent,connection_successful,connection_failed,blocked_by_firewall,dwu_limit,dwu_consumption_percent,dwu_used,dw_cpu_percent,dw_physical_data_read_percent,cache_hit_percent,cache_used_percent,local_tempdb_usage_percent"}
! at sun.reflect.GeneratedConstructorAccessor162.newInstance(Unknown Source)
! at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
! at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
! at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
! at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
! at com.microsoft.azure.management.monitor.implementation.MetricsInner.listDelegate(MetricsInner.java:261)
! at com.microsoft.azure.management.monitor.implementation.MetricsInner.access$000(MetricsInner.java:34)
! at com.microsoft.azure.management.monitor.implementation.MetricsInner$4.call(MetricsInner.java:248)
! at com.microsoft.azure.management.monitor.implementation.MetricsInner$4.call(MetricsInner.java:244)
! at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
! at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
! at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
! at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
! at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
! at rx.Observable.unsafeSubscribe(Observable.java:10327)
! at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
! at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
! at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
! at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
! at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
! at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
! at rx.Observable.subscribe(Observable.java:10423)
! at rx.Observable.subscribe(Observable.java:10390)
! at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
! at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
! at com.microsoft.azure.management.monitor.implementation.MetricsInner.list(MetricsInner.java:161)
! at externalservices.processor.azure.AzureResourceProcessor$1.operateOnClaimedCredential(AzureResourceProcessor.java:630)
! at externalservices.processor.BaseProcessor$ClaimProtectedRunnable.run(BaseProcessor.java:422)
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
! at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
! at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
! at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
! at java.lang.Thread.run(Thread.java:748)

**Comment by anirudhcavale** [comment]
As suggested by the error message it appears the query is asking for a metric not supported on data warehouses.

**Comment by praries880** [comment]
@baburajvelayudhan  can you share the code that you used to query the metric? As @anirudhcavale  said, the error suggests that the metric you queried for is not supported.

**Comment by mgsantositrs** [comment]
Any update on this issue? I'm also getting a lot of this but the weird thing is, I'm getting the metric from the a azure library function call also.

**Comment by yogeshprasad** [comment]
This happens when you try to query the metric which does not belong to the resource. You should first get the list of metric definitions by the resource id and then make use of those to get the data points for the metric for that resource.

Note: Do not assume that metrics will be the same for all resources under the same resource type.

**Comment by yogeshprasad** [comment]
@praries880 is there a way to set some setting while making the API call so azure ignores the metric which does not belongs to the resource instead of failing the entire API call?

**Comment by Kavyeah** [comment]
@yogeshprasad ,@praries880 did u find  way to set some setting while making the API call so azure ignores the metric which does not belongs to the resource instead of failing the entire API call?

**Comment by weidongxu-microsoft** [comment]
Please note that this lib is deprecated 2022 March.

Please use https://aka.ms/azsdk/java/mgmt
