### ISSUE TITLE
KeyVault secret  access policy update for Service principal fails

### ISSUE THREAD

**Issue by akshitjain** [Azure/azure-libraries-for-java#720]
While updating the keyvault access policies giving the service principal access to secrets, it fails with this:

java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.microsoft.azure.management.graphrbac.implementation.PageImpl["value"]->java.util.ArrayList[0])

Java Code for reproducing:

public void allowSecretAccessToServicePrincipal(final AzureClientMds azureClientMds,
                    final String servicePrincipal) {
        final Vault kv = getKeyVault(azureClientMds);
        final List<SecretPermissions> secretPermissionsList = new LinkedList<>();
        secretPermissionsList.add(SecretPermissions.GET);
        secretPermissionsList.add(SecretPermissions.DELETE);
        kv.update().defineAccessPolicy().forServicePrincipal(servicePrincipal)
                        .allowSecretPermissions(secretPermissionsList).attach().apply();
    }

I am using azure java sdk with version 1.20.1
Mvn tree:
[INFO] |  |  +- com.microsoft.azure:azure:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-storage:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-network:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-compute:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-graph-rbac:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-keyvault:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-batch:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-trafficmanager:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-dns:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-redis:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-appservice:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-locks:jar:1.20.1:compile
[INFO] |  |  |  +- javax.xml.bind:jaxb-api:jar:2.3.0:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-eventhub:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-cdn:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-sql:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-containerinstance:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-containerregistry:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-containerservice:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-cosmosdb:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-search:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-msi:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-monitor:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-mgmt-servicebus:jar:1.20.1:compile
[INFO] |  |  |  \- com.microsoft.azure:azure-mgmt-batchai:jar:1.20.1:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-keyvault:jar:1.2.0:compile
[INFO] |  |  |  +- com.microsoft.rest:client-runtime:jar:1.6.5:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-client-runtime:jar:1.6.5:compile
[INFO] |  |  |  +- com.microsoft.azure:azure-client-authentication:jar:1.6.5:compile

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by akshitjain** [comment]
**Please find the stack trace**	 
Resource updation failed : com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.microsoft.azure.management.graphrbac.implementation.PageImpl["value"]->java.util.ArrayList[0])	
    	 stack_trace:	 java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.microsoft.azure.management.graphrbac.implementation.PageImpl["value"]->java.util.ArrayList[0])
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.last(BlockingObservable.java:228)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.apply(CreatableUpdatableImpl.java:256)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.apply(CreatableUpdatableImpl.java:33)
	at com.adobe.mds.dcos.infra.core.azure.impl.AzureResourceHandler.apply(AzureResourceHandler.java:289)
	at com.adobe.mds.dcos.infra.core.azure.impl.resources.AzureKeyVaultHandler.allowKeyAccessToServicePrincipal(AzureKeyVaultHandler.java:161)
	at com.adobe.mds.dcos.infra.core.azure.impl.DcosInfraCreatorAzure.authorizeWorkerAccessToKeyVaultKeys(DcosInfraCreatorAzure.java:518)
	at com.adobe.mds.dcos.infra.core.azure.impl.DcosInfraCreatorAzure.createResources(DcosInfraCreatorAzure.java:413)
	at com.adobe.mds.dcos.infra.core.azure.impl.DcosInfraCreatorAzure.createInfraInner(DcosInfraCreatorAzure.java:134)
	at com.adobe.mds.dcos.infra.core.impl.DcosInfraCreatorDefault.createInfra(DcosInfraCreatorDefault.java:159)
	at com.adobe.mds.dcos.infra.core.impl.DcosInfraHandler.createDcosCluster(DcosInfraHandler.java:94)
	at com.adobe.mds.dcos.infra.core.impl.DcosOperationsHandlerImpl.lambda$createDcosCluster$0(DcosOperationsHandlerImpl.java:87)
	at com.adobe.mds.dcos.infra.core.impl.DcosOperationsHandlerImpl.call(DcosOperationsHandlerImpl.java:73)
	at com.adobe.mds.dcos.infra.core.impl.DcosOperationsHandlerImpl.createDcosCluster(DcosOperationsHandlerImpl.java:88)
	at com.adobe.mds.dcos.mdsworker.core.CreateDcosClusterAction.doCall(CreateDcosClusterAction.java:93)
	at com.adobe.mds.dcos.mdsworker.core.DcosBaseAction.call(DcosBaseAction.java:41)
	at com.adobe.mds.mdsworker.PluginActionHandler.handleMessageAndReturnStatus(PluginActionHandler.java:56)
	at com.adobe.mds.mdsworker.PluginWorkerActionFactory.handleAction(PluginWorkerActionFactory.java:59)
	at com.adobe.mds.mdsworker.PluginMessageHandler.handleMessage(PluginMessageHandler.java:58)
	at com.adobe.mds.library.worker.Worker.executeMessage(Worker.java:291)
	at com.adobe.mds.library.worker.Worker$MessageExecutor.call(Worker.java:317)
	at com.adobe.mds.library.worker.Worker$MessageExecutor.call(Worker.java:294)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.microsoft.azure.management.graphrbac.implementation.PageImpl["value"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:363)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:302)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3030)
	at com.microsoft.rest.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:137)
	at com.microsoft.rest.ServiceResponseBuilder.buildBody(ServiceResponseBuilder.java:216)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:110)
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
	at com.microsoft.azure.management.graphrbac.implementation.ServicePrincipalsInner.listDelegate(ServicePrincipalsInner.java:399)
	at com.microsoft.azure.management.graphrbac.implementation.ServicePrincipalsInner.access$100(ServicePrincipalsInner.java:45)
	at com.microsoft.azure.management.graphrbac.implementation.ServicePrincipalsInner$13.call(ServicePrincipalsInner.java:386)
	at com.microsoft.azure.management.graphrbac.implementation.ServicePrincipalsInner$13.call(ServicePrincipalsInner.java:382)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.microsoft.rest.serializer.AdditionalPropertiesDeserializer.deserialize(AdditionalPropertiesDeserializer.java:101)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:130)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:193)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.deserializeWithType(StdDeserializer.java:136)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:288)
	... 52 common frames omitted

**Comment by praries880** [comment]
@akshitjain 
* Can you let us know how you created the service principal?

* Can you turn on logging and call [this api](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-graph-rbac/src/main/java/com/microsoft/azure/management/graphrbac/implementation/ServicePrincipalsImpl.java#L57) to list the service principals to list the principal you pass into the function :
```
public void allowSecretAccessToServicePrincipal(final AzureClientMds azureClientMds,
final String servicePrincipal)
```
and see if it also hits the same null pointer exception? If it does, do kindly let us know. 
Do not post the service principal here :)

**Comment by akshitjain** [comment]
Hi @praries880 This was a jar issue. There is a jar aspectjweaver.jar  which i think wasn't compatible with the azure sdk or primarily with MSI libs.
Have removed the aspectjweaver jar  and its working fine now.
Thanks

**Comment by yaohaizh** [comment]
@akshitjain Close this issue since it was already resolved. Feel free to open it if the issue still persists.

**Comment by akshitjain** [comment]
@yaohaizh This issue is not fixed and is being faced by others as well?

Please refer this: [](https://github.com/Azure/autorest-clientruntime-for-java/issues/536)
