### ISSUE TITLE
Connect to CosmosDBAccount through Azure function app

### ISSUE THREAD

**Issue by swagulkarni** [Azure/azure-libraries-for-java#762]
I am trying to connect to CosmosDBAccount to regeneratekeys using Java SDK in Azure function app.

I am using AppServiceMSICredentials for authentication. The function app has been enabled as a managed entity.

Here is the sample code-

AppServiceMSICredentials msiCreds = new AppServiceMSICredentials(AzureEnvironment.AZURE);
Azure azure = Azure.authenticate(msiCreds).withSubscription("<my subscription id string>");
	    	
	    	// get the Cosmos DB account based on the Id
	    	CosmosDBAccount dbAccount =  azure.cosmosDBAccounts().getById("swagtestdb");

Running this code is throwing the following exception-

Exception: ClassNotFoundException: com.microsoft.azure.ProxyResource
Stack: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:54)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:51)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: com/microsoft/azure/ProxyResource
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at sun.misc.ProxyGenerator.generateClassFile(ProxyGenerator.java:451)
	at sun.misc.ProxyGenerator.generateProxyClass(ProxyGenerator.java:339)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:639)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
	at java.lang.reflect.WeakCache.get(WeakCache.java:127)
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
	at retrofit2.Retrofit.create(Retrofit.java:133)
	at com.microsoft.azure.management.batch.implementation.CertificatesInner.<init>(CertificatesInner.java:63)
	at com.microsoft.azure.management.batch.implementation.BatchManagementClientImpl.initialize(BatchManagementClientImpl.java:266)
	at com.microsoft.azure.management.batch.implementation.BatchManagementClientImpl.<init>(BatchManagementClientImpl.java:253)
	at com.microsoft.azure.management.batch.implementation.BatchManager.<init>(BatchManager.java:31)
	at com.microsoft.azure.management.batch.implementation.BatchManager.authenticate(BatchManager.java:74)
	at com.microsoft.azure.management.Azure.<init>(Azure.java:414)
	at com.microsoft.azure.management.Azure.<init>(Azure.java:129)
	at com.microsoft.azure.management.Azure$AuthenticatedImpl.withSubscription(Azure.java:390)
	at com.microsoft.azure.azure_functions_archetype.Function.rotateDBKeys(Function.java:37)
	... 16 more
Caused by: java.lang.ClassNotFoundException: com.microsoft.azure.ProxyResource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 50 more

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @yaohaizh

**Comment by swagulkarni** [comment]
Update-

I tried adding the following jar dependency in my Function module based on the following documentation-
https://github.com/Azure/autorest-clientruntime-for-java

<dependency>
	  <groupId>com.microsoft.rest</groupId>
	  <artifactId>client-runtime</artifactId>
	  <version>1.6.9</version>
</dependency>

This solved the ClassPath Exception but now its failing with another exception. Stack trace below.

Exception: SecurityException: class "com.microsoft.azure.ProxyResource"'s signer information does not match signer information of other classes in the same package
Stack: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:54)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:51)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.SecurityException: class "com.microsoft.azure.ProxyResource"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at sun.misc.ProxyGenerator.generateClassFile(ProxyGenerator.java:451)
	at sun.misc.ProxyGenerator.generateProxyClass(ProxyGenerator.java:339)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:639)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
	at java.lang.reflect.WeakCache.get(WeakCache.java:127)
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
	at retrofit2.Retrofit.create(Retrofit.java:133)
	at com.microsoft.azure.management.storage.implementation.ManagementPoliciesInner.<init>(ManagementPoliciesInner.java:51)
	at com.microsoft.azure.management.storage.implementation.StorageManagementClientImpl.initialize(StorageManagementClientImpl.java:265)
	at com.microsoft.azure.management.storage.implementation.StorageManagementClientImpl.<init>(StorageManagementClientImpl.java:253)
	at com.microsoft.azure.management.storage.implementation.StorageManager.<init>(StorageManager.java:100)
	at com.microsoft.azure.management.storage.implementation.StorageManager.authenticate(StorageManager.java:73)
	at com.microsoft.azure.management.Azure.<init>(Azure.java:415)
	at com.microsoft.azure.management.Azure.<init>(Azure.java:134)
	at com.microsoft.azure.management.Azure$AuthenticatedImpl.withSubscription(Azure.java:395)
	at com.microsoft.azure.azure_functions_archetype.Function.rotateDBKeys(Function.java:45)
	... 16 more

**Comment by yaohaizh** [comment]
@swagulkarni What the Version of  Java SDK that you are using and what's the runtime that you are using?

**Comment by swagulkarni** [comment]
I am using Java runtime.

Here are all the dependencies from my POM file

	<dependency>
	    <groupId>com.microsoft.azure</groupId>
	    <artifactId>azure-keyvault</artifactId>
	    <version>1.1.2</version>
	</dependency>
	
	<dependency>
	  <groupId>com.microsoft.rest</groupId>
	  <artifactId>client-runtime</artifactId>
	  <version>1.6.9</version>
	</dependency>
	
	<dependency>
	    <groupId>com.microsoft.azure</groupId>
	    <artifactId>azure</artifactId>
	    <version>1.22.0</version>
	</dependency>
	
	<dependency>
	    <groupId>com.microsoft.azure</groupId>
	    <artifactId>azure-documentdb</artifactId>
	    <version>2.4.0</version>
	</dependency>

**Comment by swagulkarni** [comment]
Here is the java functions library version:
        <azure.functions.java.library.version>1.0.0-beta-4</azure.functions.java.library.version>

**Comment by swagulkarni** [comment]
I am using java compiler version 1.8.

**Comment by yaohaizh** [comment]
@swagulkarni Any sample project? 

@praries880, @anuchandy It seems the project dependency has fluent and other Java SDK. Will it work if mixing the dependencies?

**Comment by swagulkarni** [comment]
@yaohaizh @anuchandy @praries880 
Note that earlier I had not added the following dependency in the POM file
<dependency>
  <groupId>com.microsoft.rest</groupId>
  <artifactId>client-runtime</artifactId>
  <version>1.6.9</version>
</dependency>

But it was throwing the class cast exception as mentioned in my first comment. Adding this dependecy resolved the class cast exception but now I am getting signature mismatch exception.

I need urgent help here as we are totally stuck with this issue.

**Comment by swagulkarni** [comment]
[azure-functions-archetype.zip](https://github.com/Azure/azure-libraries-for-java/files/3314971/azure-functions-archetype.zip)

**Comment by yaohaizh** [comment]
Some dependency are conflict, please use this tools to resolve the confilication. 

https://plugins.jetbrains.com/plugin/7179-maven-helper/versions

https://stackoverflow.com/questions/32447650/how-to-view-maven-dependency-hierarchy-in-intellij

Could you try remove this dependency from your code: 
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-keyvault</artifactId>
    <version>1.1.2</version>
</dependency>

**Comment by swagulkarni** [comment]
@yaohaizh - I had removed the below dependency but then I got the ClassCastException. I have provided the stack trace earlier. Can you please try the sample at your end and let me know the issue?

com.microsoft.azure
azure-keyvault
1.1.2

**Comment by yaohaizh** [comment]
The problems is with the client runtime dependency. You should use <dependency>
  <groupId>com.microsoft.rest</groupId>
  <artifactId>client-runtime</artifactId>
  <version>**1.6.8**</version>
</dependency>

The azure-keyvault use 1.3.4 which doesn't have the ProxyResource class.

**Comment by swagulkarni** [comment]
@yaohaizh  - I dont see any 1.3.4 version for azure-keyvault. Can you please confirm?

**Comment by prashanthmadi** [comment]
https://mvnrepository.com/artifact/com.microsoft.azure/azure-keyvault/1.1.2

![image](https://user-images.githubusercontent.com/1486808/60045372-5b202f80-968a-11e9-8b69-a966dbd7b723.png)

**Comment by prashanthmadi** [comment]
@yaohaizh 

looks like even 1.2.1 uses lower version of client runtime(v1.6.1)

https://mvnrepository.com/artifact/com.microsoft.azure/azure-keyvault/1.2.1

**Comment by yaohaizh** [comment]
I mean 

> https://mvnrepository.com/artifact/com.microsoft.azure/azure-keyvault/1.1.2
> 
> ![image](https://user-images.githubusercontent.com/1486808/60045372-5b202f80-968a-11e9-8b69-a966dbd7b723.png)

As you can see here, azure-keyvalue use 1.3.0 which doesn't have proxreource. There are the conflict of the dependency. Not sure who provide the code snippet, the sample code have conflict of client runtime.

**Comment by swagulkarni** [comment]
@yaohaizh - The problem got resolved after I changed the client-runtime version to 1.6.8

Here is my pom xml dependency now.

        <dependency>
            <groupId>com.microsoft.azure.functions</groupId>
            <artifactId>azure-functions-java-library</artifactId>
        </dependency>
        
        <dependency>
           <groupId>com.microsoft.rest</groupId>
           <artifactId>client-runtime</artifactId>
           <version>1.6.8</version>
        </dependency>

	   <dependency>
		    <groupId>com.microsoft.azure</groupId>
		    <artifactId>azure-keyvault</artifactId>
		    <version>1.2.1</version>
	   </dependency>

	
		<dependency>
		    <groupId>com.microsoft.azure</groupId>
		    <artifactId>azure</artifactId>
		    <version>1.22.0</version>
		</dependency>
		
		<dependency>
		    <groupId>com.microsoft.azure</groupId>
		    <artifactId>azure-documentdb</artifactId>
		    <version>1.12.0</version>
		</dependency>

**Comment by swagulkarni** [comment]
After incorporating the change in the jar version, the initial exception is gone but now I am getting the following error while calling the regenrateKey method on the cosmos db account:

See the below stack trace:

2019-06-25T18:42:14.332 [Error] Executed 'Functions.RotateDBKeys' (Failed, Id=470fb946-2ad2-4b8a-b870-11b43e528dfd)

Result: Failure

Exception: CloudException: polling response does not contain a valid body: {"status":"Enqueued","error":{}}

Stack: java.lang.reflect.InvocationTargetException

                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.lang.reflect.Method.invoke(Method.java:498)

                at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)

                at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:54)

                at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:51)

                at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)

                at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)

                at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)

                at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)

                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

                at java.util.concurrent.FutureTask.run(FutureTask.java:266)

                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

                at java.lang.Thread.run(Thread.java:748)

Caused by: com.microsoft.azure.CloudException: polling response does not contain a valid body: {"status":"Enqueued","error":{}}

                at com.microsoft.azure.AzureAsyncOperation.fromResponse(AzureAsyncOperation.java:148)

                at com.microsoft.azure.AzureClient$23.call(AzureClient.java:677)

                at com.microsoft.azure.AzureClient$23.call(AzureClient.java:672)

                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)

                at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:511)

                at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:466)

                at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:244)

                at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)

                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)

                at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)

                at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)

                at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)

                at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)

                at rx.Observable.unsafeSubscribe(Observable.java:10327)

                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)

                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)

                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)

                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)

                at rx.Observable.unsafeSubscribe(Observable.java:10327)

                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)

                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)

                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)

                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)

                at rx.Observable.unsafeSubscribe(Observable.java:10327)

                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)

                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)

                at rx.Observable.unsafeSubscribe(Observable.java:10327)

                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)

                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)

                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)

                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)

                at rx.Observable.unsafeSubscribe(Observable.java:10327)

                at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:81)

                at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:27)

                at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39)

                at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27)

                at rx.Observable.unsafeSubscribe(Observable.java:10327)

                at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:235)

                at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228)

                at rx.Observable.unsafeSubscribe(Observable.java:10327)

                at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:273)

                at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)

                at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)

                at rx.internal.operators.OnSubscribeRedo$5.request(OnSubscribeRedo.java:361)

                at rx.Subscriber.setProducer(Subscriber.java:211)

                at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:353)

                at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:47)

                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)

                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)

                at rx.Observable.unsafeSubscribe(Observable.java:10327)

                at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)

                at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)

                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)

                at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)

                at rx.Subscriber.setProducer(Subscriber.java:211)

                at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)

                at rx.internal.operators.SingleLiftObservableOperator$WrapSubscriberIntoSingle.onSuccess(SingleLiftObservableOperator.java:76)

                at rx.internal.operators.OnSubscribeSingle$1.onCompleted(OnSubscribeSingle.java:55)

                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onCompleted(OnSubscribeMap.java:97)

                at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:144)

                at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)

                at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)

                at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)

                at rx.Observable.unsafeSubscribe(Observable.java:10327)

                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)

                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)

                at rx.Observable.unsafeSubscribe(Observable.java:10327)

                at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:81)

                at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:27)

                at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39)

                at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27)

                at rx.Observable.unsafeSubscribe(Observable.java:10327)

                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)

                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)

                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)

                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)

                at rx.Observable.unsafeSubscribe(Observable.java:10327)

                at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)

                at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)

                at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)

                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)

                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)

                at rx.Observable.unsafeSubscribe(Observable.java:10327)

                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)

                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)

                at rx.Observable.unsafeSubscribe(Observable.java:10327)

                at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)

                at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)

                at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)

                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)

                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)

                at rx.Observable.subscribe(Observable.java:10423)

                at rx.Observable.subscribe(Observable.java:10390)

                at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)

                at rx.observables.BlockingObservable.last(BlockingObservable.java:226)

                at com.microsoft.azure.management.cosmosdb.implementation.DatabaseAccountsInner.regenerateKey(DatabaseAccountsInner.java:2023)

                at com.microsoft.azure.management.cosmosdb.implementation.CosmosDBAccountImpl.regenerateKey(CosmosDBAccountImpl.java:197)

                at com.optum.azure.functions.RotateCosmosKeysScheduler.rotateDBKeys(RotateCosmosKeysScheduler.java:107)

                ... 16 more

**Comment by swagulkarni** [comment]
Note that I notice that the cosmos keys are indeed regenerating but the call still throws the above exception at the end.

**Comment by yaohaizh** [comment]
@swagulkarni Could you provide the cloud exception details? Especially response body?

**Comment by swagulkarni** [comment]
@yaohaizh  - I have already provided the exception stack trace in my last comment here[https://github.com/Azure/azure-libraries-for-java/issues/762#issuecomment-505602067]

**Comment by yaohaizh** [comment]
The exception with payload about response which will tell details about what happened for the underlying REST API calling. Thanks.

**Comment by swagulkarni** [comment]
@yaohaizh  - I am able to have workaround on this issue by setting some exclusions in my pom.xml

	   <dependency>
		    <groupId>com.microsoft.azure</groupId>
		    <artifactId>azure-keyvault</artifactId>
		    <version>1.1.2</version>
		    <exclusions>
		      <exclusion>
		       <groupId>com.microsoft.azure</groupId>
		       <artifactId>azure-client-runtime</artifactId>
		      </exclusion>
		      <exclusion>
		       <groupId>com.microsoft.azure</groupId>
		       <artifactId>client-runtime</artifactId>
		      </exclusion>
		    </exclusions>
	   </dependency>

	
		<dependency>
		    <groupId>com.microsoft.azure</groupId>
		    <artifactId>azure</artifactId>
		    <version>1.22.0</version>
		</dependency>
		
		<dependency>
		    <groupId>com.microsoft.azure</groupId>
		    <artifactId>azure-documentdb</artifactId>
		    <version>1.12.0</version>
		</dependency>

**Comment by yaohaizh** [comment]
There is come confliction between two libs. Could you use https://mvnrepository.com/artifact/com.microsoft.azure/azure-mgmt-keyvault/1.23.0 & https://mvnrepository.com/artifact/com.microsoft.azure/azure-mgmt-cosmosdb/1.23.0
in order to provide consistent calling in your case?

**Comment by nickzhums** [comment]
@swagulkarni Hello, are you still experiencing this issue? Let us know, thanks

**Comment by yaohaizh** [comment]
Close this as this is an interaction of fluent lite/premium issue which is compatible runtime.
