### ISSUE TITLE
[BUG]  Get IllegalArgumentException when disabling Network Watcher flow log

### ISSUE THREAD

**Issue by sirhamster** [Azure/azure-libraries-for-java#846]
**Describe the bug**
Using the Azure library to disable Network Watcher flow log generates an IllegalArgumentException error stating that a required argument **workspaceResourceId** was null.  The required argument cannot be provided in the relevant functions.   

***Exception or Stack Trace***
java.lang.IllegalArgumentException: flowAnalyticsConfiguration.networkWatcherFlowAnalyticsConfiguration.workspaceResourceId is required and cannot be null.
        at com.microsoft.rest.Validator.validateClass(Validator.java:120)
        at com.microsoft.rest.Validator.validate(Validator.java:64)
        at com.microsoft.azure.management.network.implementation.NetworkWatchersInner.setFlowLogConfigurationWithServiceResponseAsync(NetworkWatchersInner.java:1871)
        at com.microsoft.azure.management.network.implementation.NetworkWatchersInner.setFlowLogConfigurationAsync(NetworkWatchersInner.java:1841)
        at com.microsoft.azure.management.network.implementation.FlowLogSettingsImpl.applyAsync(FlowLogSettingsImpl.java:44)
        at com.microsoft.azure.management.network.implementation.FlowLogSettingsImpl.apply(FlowLogSettingsImpl.java:38)
        at com.microsoft.azure.management.network.implementation.FlowLogSettingsImpl.apply(FlowLogSettingsImpl.java:21)

**To Reproduce**
A network watcher is created on the Azure account and has flow logging enabled.   Java code to disable it is run. 

***Code Snippet***
NetworkSecurityGroup nsg = azure.withDefaultSubscription()
                .networkSecurityGroups()
                .list()
                .listIterator()
                .next();

NetworkWatcher watcher = azure.withDefaultSubscription().networkWatchers().list().iterator().next();

FlowLogSettings settings = watcher.getFlowLogSettings(nsg.id());
settings.update().withoutLogging().apply();

**Expected behavior**
If argument workspaceResourceId is required, the function should be able to take it as an argument.   But parameter is not listed in [API,](https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.management.network.flowlogsettings?view=azure-java-stable) so it should not trigger an exception.   

**Screenshots**
Copy-and-pasted text output instead of screenshots.  Text shows non-null values for key variables in above code snippet.  

debug code: 
        log.info("{}", nsg.id());
        log.info("{}", settings.enabled());
        log.info("{}", settings.targetResourceId());

console output (subscription id masked):  

2019-09-25 13:33:37 INFO  steps.CloudApp.AzureSession - /subscriptions/xxxyyyzzz/resourceGroups/autotest-nsggroup/providers/Microsoft.Network/networkSecurityGroups/autotest-nsg
2019-09-25 13:33:37 INFO  steps.CloudApp.AzureSession - true
2019-09-25 13:33:37 INFO  steps.CloudApp.AzureSession - /subscriptions/xxxyyyzzz/resourceGroups/autotest-nsggroup/providers/Microsoft.Network/networkSecurityGroups/autotest-nsg

**Setup (please complete the following information):**
 - OS: Windows 10 
 - IDE : Eclipse, Version: Photon Release (4.8.0), Build id: 20180619-1200
 - Version of the Library used:  com.microsoft.azure, 1.20.1, 1.26.0

**Additional context**
n/a

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by yaohaizh** [comment]
@weidongxu-microsoft Could you help take a look at this?

**Comment by weidongxu-microsoft** [comment]
@sirhamster 
It should be same issue as https://github.com/Azure/azure-libraries-for-java/issues/767

We are checking if we could fix it in 1.27.

**Comment by weidongxu-microsoft** [comment]
Fixed in 1.27. To be release on Oct. 11th.
