### ISSUE TITLE
Exception in thread "main" java.lang.SecurityException: Signers of 'com.microsoft.azure.management.resources.implementation.$Proxy0' do not match signers of other classes in package

### ISSUE THREAD

**Issue by ArundathiGV** [Azure/azure-libraries-for-java#858]
Hi,

I am using the below azure libraries in gradle and trying list resource groups. 

```
    compile 'com.google.inject:guice:4.2.2'
    compile 'com.google.inject.extensions:guice-assistedinject:4.2.2'
    compile 'com.microsoft.azure:azure:1.26.0'
    compile 'com.microsoft.azure:azure-core:0.9.8'
    compile 'com.microsoft.azure:azure-svc-mgmt:0.9.8'
    compile 'com.microsoft.azure:azure-mgmt-resources:1.26.0'
    compile 'com.microsoft.azure:azure-mgmt-compute:1.26.0'
    compile 'com.microsoft.azure:azure-mgmt-network:1.26.0'
    compile 'com.microsoft.azure:azure-mgmt-storage:1.26.0'
    compile 'com.microsoft.azure:azure-client-runtime:1.6.8' 
    compile 'com.microsoft.azure:azure-client-authentication:1.6.14'
    compile 'com.microsoft.azure:azure-mgmt-containerservice:1.26.0'
    compile 'com.microsoft.azure:azure-tracing-util:0.9.8'
    compile 'com.microsoft.azure:adal4j:1.6.4' 
```

But I am getting the following exception

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.SecurityException: Signers of 'com.microsoft.azure.management.resources.implementation.$Proxy0' do not match signers of other classes in package
	at java.base/java.lang.ClassLoader.checkPackageSigners(ClassLoader.java:562)
	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:456)
	at java.base/java.lang.Access.defineClass(Access.java:240)
	at java.base/java.lang.reflect.Proxy$ProxyBuilder.defineProxyClass(Proxy.java:537)
	at java.base/java.lang.reflect.Proxy$ProxyBuilder.build(Proxy.java:646)
	at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$0(Proxy.java:414)
	at java.lang.reflect.Proxy$$Lambda$40.000000003C910E50.apply(Unknown Source)
	at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
	at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
	at java.base/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:412)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1004)
	at retrofit2.Retrofit.create(Retrofit.java:133)
	at com.microsoft.azure.management.resources.implementation.DeploymentsInner.<init>(DeploymentsInner.java:59)
	at com.microsoft.azure.management.resources.implementation.ResourceManagementClientImpl.initialize(ResourceManagementClientImpl.java:248)
	at com.microsoft.azure.management.resources.implementation.ResourceManagementClientImpl.<init>(ResourceManagementClientImpl.java:230)
	at com.microsoft.azure.management.resources.implementation.ResourceManagementClientImpl.<init>(ResourceManagementClientImpl.java:219)
	at test.AzureProvider.main(AzureProvider.java:22)
```
**Java version - 12
Gradle version - 5.6.2**

Please help on how to work around this problem.

**Comment by weidongxu-microsoft** [comment]
@ArundathiGV 

I've run it on java 11 and gradle 4.4.1 (that is what's latest on my debian dist), with exact same list of dependencies (+2 slf4j for logging), with code involves `Azure.authenticate(credentials)`, but not able to reproduce.

If possible please provide more information which you think might be useful. I am not sure whether we even got this Proxy interface/class under com.microsoft.azure.management.resources.implementation.

**Comment by ArundathiGV** [comment]
@weidongxu-microsoft 

I'm not sure if the issue persist in java 11. However, this issue is not reproducible even when using java 1.8.

As we have upgraded our system to 12. I want this to run on java 12. Below is the code I am using.

I have installed JDK 12 from: https://adoptopenjdk.net/ with OpenJ9 as the JVM. Could you please try it with this environment?

```
import java.util.*;

import org.slf4j.*;

import com.microsoft.azure.*;
import com.microsoft.azure.credentials.*;
import com.microsoft.azure.management.resources.implementation.*;

public class AzureProvider {

    private static final Logger _logger = LoggerFactory.getLogger(AzureProvider.class);

    public static void main(String[] args) {
        ApplicationTokenCredentials credentials = new ApplicationTokenCredentials(
            <clientId>, <tenantId>, <clientSecret>,  AzureEnvironment.AZURE);

        final ResourceManagementClientImpl resourceManagementClient = new ResourceManagementClientImpl(credentials);
        resourceManagementClient.withSubscriptionId(<subscriptionId>);

        try {
            List<ResourceGroupInner> resourceGroups = resourceManagementClient.resourceGroups().list();
            for (ResourceGroupInner rg : resourceGroups) {
                _logger.info("Got resource group {}, region {}", rg.name(), rg.location());
            }
        } catch (Exception e) {
            _logger.error("Exception {}", e);
        }
    }
} 
```

**Comment by weidongxu-microsoft** [comment]
@ArundathiGV 

This seems to be a problem with OpenJ9, not the lib.
Googled and got quite some questions on "openj9 do not match signers of other classes in package", e.g.
https://github.com/AdoptOpenJDK/openjdk-build/issues/1243

**Comment by weidongxu-microsoft** [comment]
@ArundathiGV The issue on AdoptOpenJDK is set as fixed a few days ago. Let me know if that solved your problem (not sure whether their latest build catched the fix not or though). Thanks.

**Comment by weidongxu-microsoft** [comment]
Close as I assume it is solved by AdoptOpenJDK.
