### ISSUE TITLE
[BUG] Error listing app services/functions that use key vault

### ISSUE THREAD

**Issue by maartenba** [Azure/azure-libraries-for-java#906]
**Describe the bug:**

The Azure Libraries for Java error out listing web apps/function apps when one of them has a configuration setting named `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` that references key vault (e.g. `@Microsoft.KeyVault(SecretUri=https://xxxxxxx.vault.azure.net/secrets/StorageTest/xxxxxxx)`)

***Exception or Stack Trace:***
```
com.microsoft.azure.management.appservice.DefaultErrorResponseException: Status code 500, {"Code":"InternalServerError","Message":null,"Target":null,"Details":[{"Message":null},{"Code":"InternalServerError"},{"ErrorEntity":{"Code":"InternalServerError","Message":null}}],"Innererror":null}
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.getDiagnosticLogsConfigurationDelegate(WebAppsInner.java:4977)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.access$2600(WebAppsInner.java:59)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner$112.call(WebAppsInner.java:4964)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner$112.call(WebAppsInner.java:4960)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorZip$Zip.start(OperatorZip.java:202)
	at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:143)
	at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:109)
	at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
	at rx.Subscriber.setProducer(Subscriber.java:209)
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastPath(OnSubscribeFromIterable.java:173)
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:86)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.setProducer(OnSubscribeFilter.java:104)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:63)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:34)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:45)
	at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:477)
	at com.microsoft.azure.management.resources.fluentcore.utils.PagedListConverter.loadConvertedList(PagedListConverter.java:100)
	at com.microsoft.azure.management.resources.fluentcore.utils.PagedListConverter.convert(PagedListConverter.java:66)
	at com.microsoft.azure.management.appservice.implementation.FunctionAppsImpl.wrapList(FunctionAppsImpl.java:129)
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.TopLevelModifiableResourcesImpl.list(TopLevelModifiableResourcesImpl.java:118)
	at com.microsoft.azuretools.core.mvp.model.functionapp.AzureFunctionAppMvpModel.getAzureFunctionAppsBySubscriptionId(AzureFunctionAppMvpModel.kt:94)
	at com.microsoft.azuretools.core.mvp.model.functionapp.AzureFunctionAppMvpModel.listFunctionAppsBySubscriptionId(AzureFunctionAppMvpModel.kt:82)
	at com.microsoft.azuretools.core.mvp.model.functionapp.AzureFunctionAppMvpModel.listAllFunctionApps(AzureFunctionAppMvpModel.kt:66)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.appservice.functionapp.AzureFunctionAppModulePresenter.onModuleRefresh(AzureFunctionAppModulePresenter.kt:33)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.appservice.functionapp.AzureFunctionAppModule.refreshItems(AzureFunctionAppModule.kt:51)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:95)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:161)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**To Reproduce:**

* Create a web app or function app
* Set up a key vault and update the setting `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` to reference a key vault secret

![image](https://user-images.githubusercontent.com/485230/69497600-5d0f4880-0edf-11ea-8d3e-4c4303fcc122.png)

* List web apps or function apps in the subcription using the Azure Libraries for Java

**Setup:**
 - OS: `Windows 10`
 - IDE: `n/a`
 - Version of the Library used: `1.28.0`

**Additional info:**
We learned about the issue [from here](https://github.com/JetBrains/azure-tools-for-intellij/issues/260) and started investigating.

It looks like the Azure Management API is returning a 500 status code on the following request:

```
https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{siteName}/config/logs?api-version=2018-02-01
```

The response:
```
{"Code":"InternalServerError","Message":null,"Target":null,"Details":[{"Message":null},{"Code":"InternalServerError"},{"ErrorEntity":{"Code":"InternalServerError","Message":null}}],"Innererror":null}
```

This request originates from the [`FunctionAppsImpl`](https://github.com/Azure/azure-libraries-for-java/blob/955fdc9da14c15ab94ff36b90c50869f9c09a052/azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/FunctionAppsImpl.java#L45) class in the Azure Management SDK for Java which we use under the hood. The actual call is initiated in [`WebAppsInner` on or near line 1994](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/WebAppsInner.java#L1994).

**Comment by yaohaizh** [comment]
@maartenba thanks for reporting this issue. We have rounded this issue to @ChenTanyi for further investigation.

**Comment by ChenTanyi** [comment]
@maartenba I can reproduce this issue, but 500 is server error, so I could just report it to service.
@ahmedelnably, @fabiocav could you see about this issues?

The following is steps to reproduce, and I got `storage URI is invalid` error when I deploy it using Visual Studio like https://github.com/Azure/Azure-Functions/issues/1195
## Steps to reproduce
* Create a function app or web app with:
  * .NET Core Runtime Stack (for windows OS), Windows OS, Consumption Plan type
* Enable System Assigned Identity / Use user assigned identity in function app
* Create Key Vault with access policy for function app identity
  * create key vault secret with value of `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` in function app application settings
* Update `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` with key vault reference https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references#reference-syntax

* call `https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{siteName}/config/logs?api-version=2018-02-01`
This would get a 500 error

### a java automation for these steps
```java
            final File credFile = new File(System.getenv("AZURE_AUTH_LOCATION"));
            Azure azure = Azure.configure().withLogLevel(LogLevel.NONE).authenticate(credFile)
                    .withDefaultSubscription();

            ApplicationTokenCredentials credentials = ApplicationTokenCredentials.fromFile(credFile);

            azure.resourceGroups().define(rgName)
                .withRegion(region)
                .create();

            FunctionApp func = azure.appServices().functionApps()
                .define(funcName)
                .withRegion(region)
                .withExistingResourceGroup(rgName)
                .withNewConsumptionPlan()
                .withNetFrameworkVersion(NetFrameworkVersion.V4_6)
                .withSystemAssignedManagedServiceIdentity()
                .create();

            Vault vault = azure.vaults().define(vaultName)
                .withRegion(region)
                .withExistingResourceGroup(rgName)
                .defineAccessPolicy()
                    .forServicePrincipal(credentials.clientId())
                    .allowCertificateAllPermissions()
                    .allowKeyAllPermissions()
                    .allowSecretAllPermissions()
                    .allowStorageAllPermissions()
                    .attach()
                .defineAccessPolicy()
                    .forObjectId(func.systemAssignedManagedServiceIdentityPrincipalId())
                    .allowSecretAllPermissions()
                    .attach()
                .create();

            Secret secret = vault.secrets().define(secretName)
                .withValue(func.getAppSettings().get("WEBSITE_CONTENTAZUREFILECONNECTIONSTRING").value())
                .create();

            func.update()
                .withAppSetting("WEBSITE_CONTENTAZUREFILECONNECTIONSTRING", String.format("@Microsoft.KeyVault(VaultName=%s;SecretName=%s;SecretVersion=%s)", vault.name(), secret.name(), secret.inner().secretIdentifier().version()))
                .apply();

            func = azure.appServices().functionApps().getByResourceGroup(rgName, funcName);
```

**Comment by maartenba** [comment]
Thanks!

**Comment by maartenba** [comment]
Hi folks, any news on this one from the server side?

**Comment by nickzhums** [comment]
@ahmedelnably, @fabiocav could you please take a look a this issue? thanks!

**Comment by kwasak** [comment]
Any update on this? This issue is still preventing me from deploying a function app in Rider.

**Comment by maartenba** [comment]
@ahmedelnably @fabiocav @nickzhums Are here any updates on this?

**Comment by maartenba** [comment]
@ahmedelnably @fabiocav @nickzhums Any news on the above?
