### ISSUE TITLE
[BUG]Exception when delete A record for DNS zone

### ISSUE THREAD

**Issue by yuwzho** [Azure/azure-libraries-for-java#909]
**Describe the bug**
We try to delete DNS A record with given name `domainName` by
`dnsZone.update().withoutARecordSet(domainName).apply()`. It throws an expetion, which is not from server side, even doesn't send a request out.

***Exception or Stack Trace***
```stack
java.lang.RuntimeException: invalid state - XXXXXXXX-XXXX-XXXX-XXXXXXXXXXXX: The dependency 'yyyyyyyy-yyyy-yyyy-yyyyyyyyyyyy' is already reported or there is no such dependencyKey
    at com.microsoft.azure.management.resources.fluentcore.dag.DAGNode.onSuccessfulResolution(DAGNode.java:143)
    at com.microsoft.azure.management.resources.fluentcore.dag.DAGraph.reportCompletion(DAGraph.java:166)
    at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup.processCompletedTaskAsync(TaskGroup.java:485)
    at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup.access$700(TaskGroup.java:44)
    at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup$2$3.call(TaskGroup.java:411)
    at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup$2$3.call(TaskGroup.java:408)
    at rx.internal.operators.OperatorMapNotification$MapNotificationSubscriber.onCompleted(OperatorMapNotification.java:117)
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.onCompleted(OnSubscribeMap.java:97)
    at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
    at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onCompleted(OperatorSubscribeOn.java:89)
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.onCompleted(OnSubscribeMap.java:97)
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.onCompleted(OnSubscribeMap.java:97)
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.onCompleted(OnSubscribeMap.java:97)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:656)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.onCompleted(OperatorMerge.java:281)
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.onCompleted(OnSubscribeMap.java:97)
    at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:144)
    at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
    at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
    at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
    at rx.Observable.unsafeSubscribe(Observable.java:10327)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.unsafeSubscribe(Observable.java:10327)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    at rx.Observable.unsafeSubscribe(Observable.java:10327)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    at rx.Observable.unsafeSubscribe(Observable.java:10327)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    at rx.Observable.unsafeSubscribe(Observable.java:10327)
    at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
    at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
`dnsZone.update().withoutARecordSet(domainName).apply()`

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
successfully delete the A record

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] `Linux`
 - IDE : [e.g. IntelliJ] `Zuul`
 - Version of the Library used `1.23.0`

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by yaohaizh** [comment]
@xccc-msft could you help take a look at this issue? Thanks.

**Comment by xccc-msft** [comment]
@yuwzho You need to put relative record set name when you want to delete a record set. Please check below sample code and retry. If you still face this issue, feel free to share more info.
```java
DnsZone dnsZone = zoneManager.zones().define(topLevelDomain)
                .withNewResourceGroup(RG_NAME, region)
                .defineARecordSet(aRecordSetName)
                    .withIPv4Address(ipAddress1)
                    .withIPv4Address(ipAddress2)
                    .withETagCheck()
                    .attach()
                .create();

dnsZone.update()
    .withoutARecordSet(aRecordSetName)
    .apply();
```

**Comment by yuwzho** [comment]
Thanks @xccc-msft , this exception cannot show up consistently. Will revisit this if more information gathered.
