### ISSUE TITLE
[BUG] Cannot create windows container based WebApp

### ISSUE THREAD

**Issue by tsgenge** [Azure/azure-libraries-for-java#989]
**Describe the bug**
When creating a web app on a hyper-v (windows container) service plan pulling from ACR, the command returns with an access denied attempting to authenticate with the ACR.

**To Reproduce**

1. Create a new service plan using --sku PC2 and --hyper-v.
2. Create a new web app using a container image hosted on ACR and the new service plan.

This returns with an access denied.

For linux images this works fine (it does some discovery and manually enters the ACR credentials).

Attempting to create a web app on this service plan with no image specified also does not work (actually crashes out).

The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 608, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 666, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 657, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli\azure\cli\command_modules\appservice\commands.py", line 55, in _polish_bad_errors
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\__init__.py", line 493, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli\azure\cli\command_modules\appservice\custom.py", line 131, in create_webapp
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli\azure\cli\command_modules\appservice\custom.py", line 789, in _format_fx_version
AttributeError: 'NoneType' object has no attribute 'strip'

***Code Snippet***
az webapp create -n [name] -g [rg] -p [sp] -i [namespace].azurecr.io/[image]:latest

Also fails;
az webapp create -n [name] -g [rg] -p [sp]

**Expected behavior**
The web app should create with container configuration.

**Comment by weidongxu-microsoft** [comment]
@tsgenge 

It seems to me that this is Azure CLI issue, not Azure Java SDK.

If it is actually a Java SDK issue, could you include the Java code sample?

If you are OK with it, I can transfer it to CLI's repo https://github.com/Azure/azure-cli
