### ISSUE TITLE
[BUG] withAuxiliaryCredentials only adds x-ms-authorization-auxiliary if request fails with LinkedAuthorizationFailed

### ISSUE THREAD

**Issue by thardie** [Azure/azure-libraries-for-java#993]
**Describe the bug**
Using the AzureConfigurable extension withAuxiliaryCredentials to add additional tokens when performing operations that require cross-tenant access, the code only adds the secondary credentials header (x-ms-authorization-auxiliary) if the request with the base credentials (added with the authenticate method) fails with the response "LinkedAuthorizationFailed". When doing something like creating a VM in tenant 2 using an image from tenant 1, this request returns "InvalidAuthenticationTokenTenant" and so the request is never re-tried with the additional header.

***Exception or Stack Trace***
```
634 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - --> PUT https://management.azure.com/subscriptions/<REDACTED>/resourceGroups/Terry-Test-DeleteMe/providers/Microsoft.Network/virtualNetworks/vnet178819c781?api-version=2019-06-01
635 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - Accept-Encoding: gzip
635 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - accept-language: en-US
635 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - Authorization: Bearer <REDACTED>
635 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - Connection: Keep-Alive
635 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - Content-Length: 206
635 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - Content-Type: application/json; charset=utf-8
635 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - Host: management.azure.com
635 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - User-Agent: Azure-SDK-For-Java/1.30.0 OS:Mac OS X/10.15.3 MacAddressHash:<REDACTED> Java:11.0.5 (NetworkManagementClient)
635 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - x-ms-client-request-id: <REDACTED>
635 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - 206-byte body:
{"location":"eastus2","tags":{},"properties":{"addressSpace":{"addressPrefixes":["10.1.0.0/23"]},"dhcpOptions":{"dnsServers":[]},"subnets":[{"name":"subnet1","properties":{"addressPrefix":"10.1.0.0/23"}}]}}
635 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - --> END PUT
667 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - <-- 401  https://management.azure.com/subscriptions/<REDACTED>/resourceGroups/Terry-Test-DeleteMe/providers/Microsoft.Network/virtualNetworks/vnet178819c781?api-version=2019-06-01 (30 ms, 677-byte body)
667 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - cache-control: no-cache
667 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - content-length: 677
667 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - content-type: application/json; charset=utf-8
667 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - date: Thu, 30 Jan 2020 22:33:16 GMT
667 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - expires: -1
667 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - pragma: no-cache
667 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - strict-transport-security: max-age=31536000; includeSubDomains
667 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - www-authenticate: Bearer authorization_uri="https://login.windows.net/<REDACTED>", error="invalid_token", error_description="The access token is from the wrong issuer. It must match the tenant associated with this subscription. Please use correct authority to get the token."
667 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - x-content-type-options: nosniff
667 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - x-ms-correlation-request-id: <REDACTED>
668 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - x-ms-failure-cause: gateway
668 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - x-ms-request-id: <REDACTED>
668 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - x-ms-routing-request-id: WESTUS:20200130T223316Z:<REDACTED>
668 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - 677-byte body:
{"error":{"code":"InvalidAuthenticationTokenTenant","message":"The access token is from the wrong issuer 'https://sts.windows.net/<REDACTED>/'. It must match the tenant 'https://sts.windows.net/<REDACTED>/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/<REDACTED>' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later."}}
668 [RxIoScheduler-2] INFO com.microsoft.azure.management.network.VirtualNetworks createOrUpdate  - <-- END HTTP

Exception in thread "main" com.microsoft.azure.CloudException: The access token is from the wrong issuer 'https://sts.windows.net/<REDACTED>/'. It must match the tenant 'https://sts.windows.net/<REDACTED>/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/<REDACTED>' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.: The access token is from the wrong issuer 'https://sts.windows.net/<REDACTED>/'. It must match the tenant 'https://sts.windows.net/<REDACTED>/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/<REDACTED>' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.
	at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:771)
	at com.microsoft.azure.AzureClient.access$100(AzureClient.java:33)
	at com.microsoft.azure.AzureClient$3.call(AzureClient.java:160)
	at com.microsoft.azure.AzureClient$3.call(AzureClient.java:157)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:81)
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:27)
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39)
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: retrofit2.Response.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
	... 48 more

```

**To Reproduce**
Run the code below. Exceptions at VM creation call

***Code Snippet***
```
package com.snowflake;

import com.microsoft.azure.AzureEnvironment;
import com.microsoft.azure.PagedList;
import com.microsoft.azure.management.Azure;
import com.microsoft.azure.credentials.ApplicationTokenCredentials;
import com.microsoft.azure.management.compute.VirtualMachine;
import com.microsoft.azure.management.compute.VirtualMachineSizeTypes;
import com.microsoft.azure.management.resources.Subscription;
import com.microsoft.azure.management.resources.fluentcore.arm.Region;
import com.microsoft.azure.management.storage.StorageAccount;
import com.microsoft.rest.LogLevel;
import org.apache.log4j.BasicConfigurator;
import org.apache.log4j.Logger;

public class AzureTest {

    static Logger logger = Logger.getLogger(AzureTest.class);

    public static void main(String[] args) {
        BasicConfigurator.configure();

        ApplicationTokenCredentials secondaryCredentials =
                new ApplicationTokenCredentials(
                        "<app ID>",
                        "<tenant1>",
                        "<App ID password>",
                        AzureEnvironment.AZURE);
        ApplicationTokenCredentials credentials =
                new ApplicationTokenCredentials(
                        "<App ID>",
                        "<Tenant 2>",
                        "<App ID password>",
                        AzureEnvironment.AZURE);

        Azure azure = Azure.configure()
                .withLogLevel(LogLevel.BODY_AND_HEADERS)
                .withAuxiliaryCredentials(credentials)
                .authenticate(secondaryCredentials)
                .withSubscription("<Tenant 2 subscription>");

        VirtualMachine vm = azure.virtualMachines().define("Terry-Test-Deleteme")
                .withRegion(Region.US_EAST2)
                .withExistingResourceGroup("Terry-Test-DeleteMe")
                .withNewPrimaryNetwork("10.1.0.0/23")
                .withPrimaryPrivateIPAddressDynamic()
                .withoutPrimaryPublicIPAddress()
                .withLinuxCustomImage("<Source custom image name>")
                .withRootUsername("root")
                .withRootPassword("<password>")
                .withSize(VirtualMachineSizeTypes.STANDARD_DS1_V2)
                .create();
        System.out.print(vm.name());
    }
}
```
**Expected behavior**
VM should be created in Tenant 2 with the image from Tenant 1

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Mac OS X/10.15.3
 - IDE : IntelliJ 2019.3.2
 - Azure-SDK-For-Java/1.30.0

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by thardie** [comment]
Turns out his was an issue with the order of the credentials. I needed to switch the primary and secondary credentials, then this worked.
